name: Darin Bushman
favicon: null
layout_spectrum: 0.93308
typography_spectrum: 0.48178889066912234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#515151'
    - '#a1a2a7'
    - '#252821'
    - '#000000'
    - '#a37845'
  brandStrength: 0.5824252108577639
  lightness: 0.033886855468153954
  saturation: 0.9176926051732153
  rhythmicContrast: 0.7586771233472973
purpose: []
