name: Darin Bushman
favicon: null
layout_spectrum: 0.88234
typography_spectrum: 0.17855885811150074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5625
  lightness: 0.7033974605146796
  saturation: 0.2009679740294814
  rhythmicContrast: 0.4707967098802328
purpose: []
