name: Darin Bushman
favicon: null
layout_spectrum: 0.2576581386383623
typography_spectrum: 0.48178889066912234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5824252108577639
  lightness: 0.033886855468153954
  saturation: 0.9176926051732153
  rhythmicContrast: 0.7586771233472973
purpose: []
